apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendertron
  labels:
    app: rendertron
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rendertron
  template:
    metadata:
      labels:
        app: rendertron
    spec:
      containers:
      - name: rendertron
        image: chriskolenko/dynamic-ssr:0.1.0
        ports: 
        - containerPort: 80